[package]
name = "Thread"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.1", features = ["thread-pool"] }
tokio = { version = "0.3", features = ["full"] }